config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  # devise_scope :user do
  #   get "sign_in", :to => "users/sessions#new"
  #   get "sign_out", :to => "users/sessions#destroy" 
  # end

  root to: "user_infos#index"

  get 'user_infos/search'

  resources :rooms, only: [:index, :new, :create] do
    resources :messages, only: [:index, :create]
  end
 
  resources :user_infos do
    collection do
      get 'pre_page'
      get 'false'
    end
    resources :favorites, only: [:index, :create, :destroy]
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user, optional: true #加えた
  belongs_to :user_info

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_user_info, only: [:create, :destroy]
  before_action :authenticate_user!

  def index
    @users = User.all
    @favorite_user_infos = current_user.favorite_user_infos #情報を取ってる
    @favorite_users = current_user.user_info.favorite_users #ユーザーを取ってる
    x = current_user.favorite_user_infos.pluck(:user_id)
    y = current_user.user_info.favorite_users.ids
    z = x & y
    @match = User.where(id: z)
  end

  # def create
  #   favorite = current_user.favorites.build(user_info_id: params[:user_info_id])
  #   favorite.save
  #   redirect_to root_path
  # end

  # def destroy
  #   favorite = Favorite.find_by(user_info_id: params[:user_info_id], user_id: current_user.id)
  #   favorite.destroy
  #   redirect_to root_path
  # end

  def create
    # @user_info = UserInfo.find(params[:user_info_id])
    favorite = current_user.favorites.build(user_info_id: params[:user_info_id])
    favorite.save
  end

  def destroy
    # @user_info = UserInfo.find(params[:user_info_id])
    favorite = Favorite.find_by(user_info_id: params[:user_info_id], user_id: current_user.id)
    favorite.destroy
  end

  private
  def set_user_info
    @user_info = UserInfo.find(params[:user_info_id])
  end

  
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if user_signed_in? && user_info.user_id != current_user.id %>
  <% if user_info.favorited_by?(current_user) %>
    <p class="followed_btn"><%=link_to "お気に入り済", user_info_favorite_path(user_info.id, 1), class: "white", method: :delete, remote: true %></p>
    <% else %>
    <p class="follow_btn"><%=link_to "お気に入り", user_info_favorites_path(user_info.id), class: "white", method: :post, remote: true %></p>
  <% end %>
<% end %>

app/views/favorites/_favorite_search.html.erb
<% if user_signed_in? && @result.user_id != current_user.id %>
  <% if @result.favorited_by?(current_user) %>
    <p class="followed_btn"><%=link_to "お気に入り済", user_info_favorite_path(@result.id, 1), class: "white", method: :delete, remote: true %></p>
  <% else %>
    <p class="follow_btn"><%=link_to "お気に入り", user_info_favorites_path(@result.id), class: "white", method: :post, remote: true %></p>
  <% end %>
<% end %>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @user_info.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {user_info: @user_info}) %>");

app/views/favorites/create_search.js.erb
<%# $('#favorites_search_buttons_<%= @user_info.id %>').html("<%= j(render partial: 'favorites/favorite_search', locals: {user_info: @user_info}) %>"); %>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @user_info.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {user_info: @user_info}) %>")

app/views/favorites/destroy_search.js.erb
$('#favorites_buttons_<%= @user_info.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {user_info: @user_info}) %>");

app/views/favorites/index.html.erb
<div class='chat-room-form'>
  <h1>マッチしたユーザー</h1>
  <% @users.each do |user| %>
  <% if current_user.id == user.id %>
    <ul class="users">
      <li class="user">
      <% @match.each do |match| %>
        <p><%= match.nickname %></p>
        <%= link_to 'チャットする', messages_path, class: 'mypage_btn' %>
      <% end %>
      </li>
    </ul>
  <% end %>
  <% end %>
</div>