config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  # devise_scope :user do
  #   get "sign_in", :to => "users/sessions#new"
  #   get "sign_out", :to => "users/sessions#destroy" 
  # end

  root to: "user_infos#index"

  get 'user_infos/search'

  resources :rooms, only: [:index, :new, :create] do
    resources :messages, only: [:index, :create]
  end
 
  resources :user_infos do
    collection do
      get 'pre_page'
      get 'false'
    end
    resources :favorites, only: [:index, :create, :destroy]
  end
end

app/models/user_info.rb
class UserInfo < ApplicationRecord
  has_one_attached :image
  belongs_to :user, optional: true #加えた

  # 非同期用
  has_many :favorites, dependent: :destroy
  # 非同期用
  
  has_many :favorite_users, through: :favorites, source: :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :area
  belongs_to_active_hash :people_num

  with_options presence: true do
    validates :text
    # validates :image
    validates :area
    validates :people_num
  end

  validate :image_presence

  def image_presence
    if image.attached?
      if !image.content_type.in?(%('image/jpeg image/png'))
        errors.add(:image, 'にはjpegまたはpngファイルを添付してください')
      end
    else
      errors.add(:image, 'ファイルを添付してください')
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/controllers/user_infos_controller.rb
class UserInfosController < ApplicationController
  before_action :search_user_info, only: [:index, :search]
  before_action :authenticate_user!, except: [:index, :search]

  def index
    @promotion_male = UserInfo.joins(:user).where(users: { gender: "男"}).count
    @promotion_female = UserInfo.joins(:user).where(users: { gender: "女"}).count
    unless user_signed_in?
      @user_infos = UserInfo.all.order(updated_at: :desc)
      set_user_info_column
      return
    end
    if current_user.gender == "女"
      @user_infos = UserInfo.joins(:user).where(users: { gender: "男"}).order(updated_at: :desc)
      set_user_info_column
    elsif current_user.gender == "男"
      @user_infos = UserInfo.joins(:user).where(users: { gender: "女"}).order(updated_at: :desc)
      set_user_info_column
    end
  end

  def search
    @promotion_male = UserInfo.joins(:user).where(users: { gender: "男"}).count
    @promotion_female = UserInfo.joins(:user).where(users: { gender: "女"}).count
    unless user_signed_in?
      @results = @p.result.all.order(id: "DESC")
      set_user_info_column
      return
    end
    if current_user.gender == "女"
      @results = @p.result.joins(:user).where(users: { gender: "男"}).order(updated_at: :desc)
      set_user_info_column
    elsif current_user.gender == "男"
      @results = @p.result.joins(:user).where(users: { gender: "女"}).order(updated_at: :desc)
      set_user_info_column
    end
  end

  def new
    if UserInfo.where(user_id: current_user.id).present?
      redirect_to action: :false
    else
      @user_info = UserInfo.new
    end
  end

  def create
    @user_info = UserInfo.new(user_info_params)
    if @user_info.valid?
      @user_info.save
      flash[:notice] = 'Successfully!'
      redirect_to pre_page_user_infos_path
    else
      render :new
    end
  end

  def edit
    @user_info = UserInfo.find(params[:id])
  end

  def update
    @user_info = UserInfo.find(params[:id])
    if @user_info.update(user_info_params)
      flash[:notice] = 'Successfully!'
       redirect_to pre_page_user_infos_path
    else
      render :edit
    end
  end

  def destroy
  end

  def pre_page
    @user_infos = UserInfo.all
  end


  private

  def search_user_info
    @p = UserInfo.ransack(params[:q])
  end

  def set_user_info_column
    @user_info_area = UserInfo.select("area_id").distinct  # 重複なくnameカラムのデータを取り出す
    @user_info_people_num = UserInfo.select("people_num_id").distinct  # 重複なくnameカラムのデータを取り出す
  end

  def user_info_params
    params.require(:user_info).permit(:gender, :image, :text, :people_num_id, :area_id).merge(user_id: current_user.id)
  end

end

app/helpers/user_infos_helper.rb
module UserInfosHelper
end

app/views/user_infos/edit.html.erb
<div class="user_info_contents">
  <div class="user_info_main">
    <h2 class="user_info_title">あなたの情報を入力</h2>
    <%= form_with model: @user_info, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 画像 %>
    <div class="user_field">
      <div class="weight-bold-text">
        あなたたちの写真<br>※横長の写真を選択してください。
        <br class="br"><span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <%= f.file_field :image, id:"user_info_image" %>
      </div>
    </div>
    <%# 画像 %>


    <%# あなたの説明 %>
    <div class="user_field">
      <div class="weight-bold-text">
        あなたたちの一言！
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :text, class:"user_text", id:"info", placeholder:"これから出会う方にひとこと伝えましょう！" ,rows:"3" ,maxlength:"30" %>
    </div>
    <%# /あなたの説明 %>

    <%# あなたたちの詳細 %>
    <div class="user_field">
      <div class="weight-bold-text">
        あなたたちの人数
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:people_num_id, PeopleNum.all, :id, :name, {}, {class:"select-box", id:"user_info_people_num"}) %>
    <div class="user_field">
      <div class="weight-bold-text">
        あなたたちのいるエリア
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:area_id, Area.all, :id, :name, {}, {class:"select-box", id:"item-user_info_area"}) %>
    </div>
    <%# /あなたたちの詳細 %>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "登録する" ,class:"btn" %><br>
      <%=link_to 'マイページに戻る', pre_page_user_infos_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  
</div>

app/views/user_infos/false.html.erb
<div class="false">
  <div class="false_sign">
    <p>チャット相手が選択されていません。<br>チャット相手を選択してルームを作成してください。</p>
    <%= link_to 'マイページへ戻る', pre_page_user_infos_path %>
  </div>
</div>

app/views/user_infos/followers.html.erb
<h1>Users#followers</h1>
<p>Find me in app/views/users/followers.html.erb</p>

<% @user_infos.each do |user_info| %>
  <hr>
  <p><span>email: </span><%= link_to user_info.user.email, user_info_path(user_info.id) %></p>
    <% if current_user.id != user_info.user_id %>
        <% if user_info.followed_by?(current_user.user_info) %>
            <p><%=link_to "フォロー済み", user_info_relationships_path(user_info.id), method: :delete %></p>
        <% else %>
            <p><%=link_to "フォローする", user_info_relationships_path(user_info.id), method: :post %></p>
        <% end %>
    <% end %>
<% end %>

app/views/user_infos/follows.html.erb
<h1>Users#follows</h1>
<p>Find me in app/views/users/follows.html.erb</p>

<% @user_infos.each do |user_info| %>
  <hr>
  <p><span>email: </span><%= link_to user_info.user.email, user_info_path(user_info.id) %></p>
    <% if current_user.id != user_info.user_id %>
        <% if user_info.followed_by?(current_user.user_info) %>
            <p><%=link_to "フォロー済み", user_info_relationships_path(user_info.id), method: :delete %></p>
        <% else %>
            <p><%=link_to "フォローする", user_info_relationships_path(user_info.id), method: :post %></p>
        <% end %>
    <% end %>
<% end %>

app/views/user_infos/index.html.erb
<div class="content">
  <header>

    <div class="nav">
      <div class="title">
      <%= link_to 'S U G U', root_path, class: 'title' %>
      </div>
      <div id="nav-drawer">
        <input id="nav-input" type="checkbox" class="nav-unshown">
        <label id="nav-open" for="nav-input"><span></span></label>
        <label class="nav-unshown" id="nav-close" for="nav-input"></label>
        <div id="nav-content">
          <ul class="right_header">

          <% if user_signed_in? %>
            <li class="user_name">
            <%= current_user.nickname %>さん
            </li>
            <li class="logout">
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'header_btn' %>
            </li>
          <% else %>
            <li class="signin">
            <%= link_to '新規登録', new_user_registration_path, class: 'header_btn' %>
            </li>
            <li class="login">
            <%= link_to 'ログイン', new_user_session_path, class: 'header_btn' %>
            </li>
          <% end %>

          <% if user_signed_in? && current_user.user_info.present? %>
            <li class="new_user_info">
            <%= link_to 'マイページ', pre_page_user_infos_path, class: 'header_btn' %>
            </li>
          <% elsif user_signed_in? && unless current_user.user_info.present? %>
            <li class="enter">
            <%= link_to '投稿する', new_user_info_path, class: 'header_btn' %>
            </li>
          <% end %>
          <% end %>

          </ul>
        </div>
      </div>
    </div>

    <div class="border">
      <%= link_to 'S U G U', root_path, class: 'title' %>
      <ul class="right_header">
      <% if user_signed_in? %>
        <li class="user_name">
        <%= current_user.nickname %>さん
        </li>
        <li class="logout">
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'header_btn' %>
        </li>
      <% else %>
        <li class="signin">
        <%= link_to '新規登録', new_user_registration_path, class: 'header_btn' %>
        </li>
        <li class="login">
        <%= link_to 'ログイン', new_user_session_path, class: 'header_btn' %>
        </li>
      <% end %>

      <% if user_signed_in? && current_user.user_info.present? %>
        <li class="new_user_info">
        <%= link_to 'マイページ', pre_page_user_infos_path, class: 'header_btn' %>
        </li>
      <% elsif user_signed_in? && unless current_user.user_info.present? %>
        <li class="enter">
        <%= link_to '投稿する', new_user_info_path, class: 'header_btn' %>
        </li>
      <% end %>
      <% end %>

      </ul>
    </div>
  </header>

  <div class="top_main">
    <div class="left">
      <p>S U G Uは、<br>「今すぐ会いたい」を形にする<br>「複数人」対「複数人」の<br>マッチングアプリです。</p>
    </div>
    <div class="right">
      <div class="proportion">
        <h2>現在の男女比</h2>
        <span class="sex otoko">男 </span><span class="sex"><%= @promotion_male %></span><span class="brbr">人</span><br class="brbr">
        <span class="none">：</span>
        <span class="sex onna"> 女 </span><span class="sex"><%= @promotion_female %></span><span class="brbr">人</span>
      </div>
      <div class="wating">
        <h2 class="taiki">待機中グループを<br class="br375">検索</h2>
        <%= search_form_for @p, url: user_infos_search_path do |f| %>
        <div class="try">
        <%= f.label :area_id_eq, 'エリア' %>
        <%= f.collection_select :area_id_eq, Area.all, :id, :name, include_blank: '指定なし' %>
        </div>
        <br>
        <div class="try">
        <%= f.label :people_num_id_eq, '人数' %>
        <%= f.collection_select :people_num_id_eq, PeopleNum.all, :id, :name, include_blank: '指定なし' %>
        </div>
        <br>
        <div class="s">
        <%= f.submit '探してみる', class: "search_btn" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render partial: 'layouts/flash' %>


<% unless user_signed_in? %>
<div class="about_app">
  <div class="what_app">
    <div class="explain">
      <p class="bold" style="border-bottom: 1px solid #806000">どんなマッチングアプリ？</p><br>
      <p>S U G Uは、今すぐに異性との飲み会を開きたい人に向けたマッチングアプリです。他のアプリと違う点は２つあります。一つは「複数人」対「複数人」で出会えるということ。もう一つは今すぐ会えるということです。</p>
    </div>
  </div>
  <div class="why_app">
    <div class="explain">
      <p class="bold" style="border-bottom: 1px solid #806000">なぜすぐ会えるのか？</p><br>
      <p>「待機中のグループ一覧」にはあなたと同じように、今すぐに飲み会を開きたいユーザーがいらっしゃいます。そんな方々が集まっているので、すぐに会うことができます。またの上の方に表示されているユーザーほど、投稿時間が浅く、マッチする確率が上がります。</p>
    </div>
  </div>
</div>

<div class="how_to_use">
  <h2 class="gold">S U G Uの<br class="br320">使い方</h2>
  <p class="exp"><span class="bold under_line">STEP1</span><br class="br"> 現在の自分の状況を<br class="br320">投稿する</p>
  <p class="exp"><span class="bold under_line">STEP2</span><br class="br"> 他のユーザーの投稿を<br class="br375">お気に入りをする</p>
  <p class="exp"><span class="bold under_line">STEP3</span><br class="br"> 相手も自分の投稿を<br class="br375"><br class="br320">お気に入りしたら<br class="br320">マッチング</p>
  <p class="exp"><span class="bold under_line">STEP4</span><br class="br"> マッチしたユーザー<br class="br320">との<br class="br375">チャットルームを<br class="br320">作成</p>
  <p class="exp"><span class="bold under_line">STEP5</span><br class="br"> チャットをスタート</p>
  <p class="asap">早速ログインして、<br class="br320">素晴らしい出会いを見つけてください</p>
</div>
<% end %>



<div class="top_page">
  <div class="flex">
    <h2 class="gold">待機中の<br class="br">グループ一覧</h2>
  </div>
  <div class="explain_flex">
    <p style="font-size:17px;">上に表示されている投稿ほど<br class="br375">最新のものです。<br>見逃さずにお気に入りを<br class="br">しましょう。</p>
  </div>
  <p class="caution">※ログイン後、お気に入りを<br class="br">することができます。</p>
  <ul class="groups">
    <% @user_infos.each do |user_info| %>
      <li class="list">
        <div class='user_infos'>
          <div class="user_img">
            <!-- ネットのフォローボタン  -->
            <%= image_tag user_info.image.variant(resize:'380x380'), class: "user_img" if user_info.image.attached? %>
            <div id="favorites_buttons_<%= user_info.id %>">
              <%= render partial: 'favorites/favorite', locals: { user_info: user_info} %>
            </div>
            <!-- ネットのフォローボタン -->
            <div class="time">
            <%= user_info.updated_at.to_s(:datetime_jp) %>
            </div>
            <div class="top">
              <p class="nickname"><%= user_info.user.nickname %></p>
              <span>/</span>
              <p class="area"><%= user_info.area.name %></p>
              <span>/</span>
              <p class="people_num"><%= user_info.people_num_id %>人</p>
            </div>
            <div class="down">
              <p class="user_info_text">ひとこと：<%= user_info.text %></p>
            </div>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

app/views/user_infos/new.html.erb
<div class="user_info_contents">
  <div class="user_info_main">
    <h2 class="user_info_title">あなたたちの情報を入力</h2>
    <%= form_with model: @user_info, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 画像 %>
    <div class="user_field">
      <div class="weight-bold-text">
        あなたたちの写真<br>※横長の写真を選択してください。
        <br class="br"><span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <%= f.file_field :image, id:"user_info_image" %>
      </div>
    </div>
    <%# 画像 %>


    <%# あなたの説明 %>
    <div class="user_field">
      <div class="weight-bold-text">
        あなたたちの一言！
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :text, class:"user_text", id:"info", placeholder:"これから出会う方にひとこと伝えましょう！" ,rows:"3" ,maxlength:"30" %>
    </div>
    <%# /あなたの説明 %>

    <%# あなたたちの詳細 %>
    <div class="user_field">
      <div class="weight-bold-text">
        あなたたちの人数
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:people_num_id, PeopleNum.all, :id, :name, {}, {class:"select-box", id:"user_info_people_num"}) %>
    <div class="user_field">
      <div class="weight-bold-text">
        あなたたちのいるエリア
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:area_id, Area.all, :id, :name, {}, {class:"select-box", id:"item-user_info_area"}) %>
    </div>
    <%# /あなたたちの詳細 %>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "登録する" ,class:"btn" %><br>
      <%=link_to 'トップページに戻る', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>
  
</div>

app/views/user_infos/pre_page.html.erb
<div class="pre_content">
  <header>

    <div class="nav">
      <div class="title">
      <%= link_to 'S U G U', root_path, class: 'title' %>
      </div>
      <div id="nav-drawer">
        <input id="nav-input" type="checkbox" class="nav-unshown">
        <label id="nav-open" for="nav-input"><span></span></label>
        <label class="nav-unshown" id="nav-close" for="nav-input"></label>
        <div id="nav-content">
          <ul class="right_header">
          <% if user_signed_in? %>
            <li class="user_name">
            <%= current_user.nickname %>さん
            </li>
            <div class="to_root">
            <%= link_to 'トップページ', root_path, class: 'header_btn' %>
            </div>
            <li class="logout">
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'header_btn' %>
            </li>
          <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="border">
      <%= link_to 'S U G U', root_path, class: 'title' %>
      <ul class="right_header">
      <% if user_signed_in? %>
        <li class="user_name">
        <%= current_user.nickname %>さん
        </li>
        <div class="to_root">
        <%= link_to 'トップページ', root_path, class: 'mypage_btn' %>
        </div>
      <% end %>
      </ul>
    </div>
  </header>

  <div class="mypage">
    <div class="my">
      <div class="mypage_btns">
        <h2>マイページ</h2>
        <% @user_infos.each do |user_info| %>
        <% if current_user.id == user_info.user_id %>
        <div class="edit_user_info">
        <%= link_to '投稿を編集する', edit_user_info_path(user_info.id), class: 'mypage_btn' %>
        </div><br>
        <div class="matchin_user">
        <%= link_to 'ルーム作成', new_room_path, class: 'mypage_btn' %>
        </div><br>
        <div class="matchin_user">
        <%= link_to 'チャットルームへ', rooms_path, class: 'mypage_btn' %>
        </div><br>
      </div>
    </div>
  </div>
</div>

<%= render partial: 'layouts/flash' %>

  
<div class='pre_user_infos'>
  <div class="flex">
    <h2 class="gold">あなたの今の投稿<h2>
  </div>
  <div class="pre_user_img">
  <%= image_tag user_info.image.variant(resize:'400x400'), class: "user_img" if user_info.image.attached? %>
  </div>
  <div class="time">
  <%= user_info.updated_at.to_s(:datetime_jp) %>
  </div>
  <div class="ul_top">
    <p class="nickname"><%= user_info.user.nickname %></p>
    <span>/</span>
    <p class="area"><%= user_info.area.name %></p>
    <span>/</span>
    <p class="people_num"><%= user_info.people_num_id %>人</p>
  </div>
  <div class="down">
    <p class="user_info_text">ひとこと：<%= user_info.text %></p>
  </div>
    <% end %>
  <% end %>
<% unless user_signed_in?%>
  <div class="enter">
  <%= link_to '情報を入力する', new_user_info_path, class: 'mypage_btn' %>
  </div><br>
<% end %>
</div>

app/views/user_infos/search.html.erb
<div class="content">
  <header>

    <div class="nav">
      <div class="title">
      <%= link_to 'S U G U', root_path, class: 'title' %>
      </div>
      <div id="nav-drawer">
        <input id="nav-input" type="checkbox" class="nav-unshown">
        <label id="nav-open" for="nav-input"><span></span></label>
        <label class="nav-unshown" id="nav-close" for="nav-input"></label>
        <div id="nav-content">
          <ul class="right_header">
          <% if user_signed_in? %>
            <li class="user_name">
            <%= current_user.nickname %>さん
            </li>
            <li class="new_user_info">
            <%= link_to 'マイページ', pre_page_user_infos_path, class: 'header_btn' %>
            </li>
            <li class="logout">
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'header_btn' %>
            </li>
          <% else %>
            <li class="signin">
            <%= link_to '新規登録', new_user_registration_path, class: 'header_btn' %>
            </li>
            <li class="login">
            <%= link_to 'ログイン', new_user_session_path, class: 'header_btn' %>
            </li>
          <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="border">
      <%= link_to 'S U G U', root_path, class: 'title' %>
      <ul class="right_header">
      <% if user_signed_in? %>
        <li class="user_name">
        <%= current_user.nickname %>さん
        </li>
        <li class="logout">
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'header_btn' %>
        </li>
        <li class="new_user_info">
        <%= link_to 'マイページ', pre_page_user_infos_path, class: 'header_btn' %>
        </li>
      <% else %>
        <li class="signin">
        <%= link_to '新規登録', new_user_registration_path, class: 'header_btn' %>
        </li>
        <li class="login">
        <%= link_to 'ログイン', new_user_session_path, class: 'header_btn' %>
        </li>
      <% end %>
      </ul>
    </div>
  </header>

  <div class="top_main">
    <div class="left">
    </div>
    <div class="right">
      <div class="proportion">
        <h2>現在の男女比</h2>
        <span class="sex otoko">男 </span><span class="sex"><%= @promotion_male %> ：<span class="sex onna"> 女 </span><span class="sex"><%= @promotion_female %></span>
      </div>
      <div class="wating">
        <h2>待機中グループを検索</h2>
        <%= search_form_for @p, url: user_infos_search_path do |f| %>
        <div class="try">
        <%= f.label :area_id_eq, 'エリア' %>
        <%= f.collection_select :area_id_eq, Area.all, :id, :name, include_blank: '指定なし' %>
        </div>
        <br>
        <div class="try">
        <%= f.label :people_num_id_eq, '人数' %>
        <%= f.collection_select :people_num_id_eq, PeopleNum.all, :id, :name, include_blank: '指定なし' %>
        </div>
        <br>
        <%= f.submit '探してみる', class: "search_btn" %>
      </div>
      <% end %>
    </div>
  </div>
</div>



<div class="search_top">
  <div class="flex">
    <h2 class="gold">検索結果</h2>
  </div>
  <div class="explain_flex">
    <p style="font-size:17px;">画面上部の投稿は、<br class="br">最新の合コン情報です。<br>見逃さずにお気に入りをしましょう。</p>
  </div>
  <div class="root_path">
  <%= link_to 'トップページへ戻る', root_path %>
  </div>
</div>
<%# 検索結果の個数で条件分岐 %>
<div class="top_page">
  <% if @results.length != 0 %>
    <ul class="groups">
      <% @results.each do |result| %>
        <% @result = result%>
        <li class="list">
          <div class='user_infos'>
            <div class="user_img">
            <!-- ネットのフォローボタン  -->
            <%= image_tag result.image.variant(resize:'400x400'), class: "user_img" if result.image.attached? %>
            <div id="favorites_buttons_<%= result.id %>">
              <%= render partial: 'favorites/favorite_search', locals: { user_info: result} %>
            </div>
            <!-- ネットのフォローボタン  -->
            <div class="time">
            <%= result.updated_at.to_s(:datetime_jp) %>
            </div>
            <div class="top">
              <p class="nickname"><%= result.user.nickname %></p>
              <span>/</span>
              <p class="area"><%= result.area.name %></p>
              <span>/</span>
              <p class="people_num"><%= result.people_num_id %>人</p>
            </div>
            <div class="down">
              <p class="user_info_text">ひとこと：<%= result.text %></p>
            </div>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p class="sorry">申し訳ございません、現在該当するグループはいません。<br>違う条件でも検索してみてください。</p>
  <% end %>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>