config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  # devise_scope :user do
  #   get "sign_in", :to => "users/sessions#new"
  #   get "sign_out", :to => "users/sessions#destroy" 
  # end

  root to: "user_infos#index"

  get 'user_infos/search'

  resources :rooms, only: [:index, :new, :create] do
    resources :messages, only: [:index, :create]
  end
 
  resources :user_infos do
    collection do
      get 'pre_page'
      get 'false'
    end
    resources :favorites, only: [:index, :create, :destroy]
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users
  has_many :users, through: :room_users
  has_many :messages
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @favorite_user_infos = current_user.favorite_user_infos #情報を取ってる
    @favorite_users = current_user.user_info.favorite_users #ユーザーを取ってる
    x = current_user.favorite_user_infos.all.pluck(:user_id)
    y = current_user.user_info.favorite_users.ids
    z = x & y
    @match = User.where(id: z)
  end

  def new
    @room = Room.new
    @favorite_user_infos = current_user.favorite_user_infos #情報を取ってる
    @favorite_users = current_user.user_info.favorite_users #ユーザーを取ってる
    x = current_user.favorite_user_infos.pluck(:user_id)
    y = current_user.user_info.favorite_users.ids
    z = x & y
    @matched = User.where(id: z)

    u = current_user.rooms.includes(:users).map{|room| room.users.ids}.flatten.uniq
    a = z - u
    @match = User.where(id: a)
  end

  def create
    @room = Room.new(room_params)
    if @room.user_ids.length == 2
      @room.save
      redirect_to rooms_path
    else
      redirect_to false_user_infos_path
    end
  end


  private

  def room_params
    params.require(:room).permit(user_ids:[])
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<div class='wrapper'>
  
  <p class="fixed">左上のメニューボタンで<br>チャットを始めます</p>

  <div class='side-bar'>
    <div class="ahh">
    <%= render "messages/side_bar"%>
    </div>

    <div class="m_nav">
      <div id="m-nav-drawer">
        <input id="m-nav-input" type="checkbox" class="m-nav-unshown">
        <label id="m-nav-open" for="m-nav-input"><span></span></label>
        <label class="m-nav-unshown" id="m-nav-close" for="m-nav-input"></label>
        <div id="m-nav-content">
          <div class="m_side-bar-header">
            <div class="m_header-name">
              <%= current_user.nickname %>さん
            </div>
            <div class="m_create-room">
              <%= link_to "マイページに戻る", pre_page_user_infos_path, class: 'z' %>
            </div>
          </div>
          <div class="m_rooms">
            <p style="color:white;">名前を押してチャットを始めます</p>
            <% current_user.rooms.each do |room| %>
              <div class="m_room">
                <div class="m_room-name">
                <% t = room.room_users.where.not(user_id: current_user.id).pluck(:user_id) %>
                <% @chat_user = User.find_by(id: t) %>
                <p class="w"><%= link_to @chat_user.nickname, room_messages_path(room), class: 'w' %></p>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<div class='new_room'>
  <%=form_with model: @room, local: true do |f|%>
  <div class="new_room_form">
    <h2>新規チャットルーム</h2>
    <div class='room_form'>
      <select name="room[user_ids][]" class="room_user_select">
        <option value="">マッチしたユーザーを選択できます</option>
        <% @match.each do |match| %>
          <option value=<%= match.id %>><%= match.nickname %></option>
        <% end %>
      </select>
      <p>※選択肢にユーザー名が現れない場合は<br class="br">マッチしていないか、<br class="br">すでにチャットルームが存在しています。</p>
      <input name="room[user_ids][]" type="hidden" value=<%=current_user.id%>>
    </div>
    <div class='create_room'>
      <%= f.submit class: 'create_room_btn'%>
    </div>
    <div class="redirect_mypage">
      <%= link_to 'マイページへ戻る', pre_page_user_infos_path %>
    </div>
    <div class="matchin_user">
    <%= link_to 'チャットルームへ', rooms_path %>
    </div>
  </div>
  <% end %>
</div>


<% if @matched.exists?%>

<div class="matched_users">
  <div class="flex">
    <h2 class="gold">マッチしたユーザー</h2>
  </div>
  <ul>
  <% @matched.each do |matched| %>
    <li class="list">
      <div class="matched_top">
        <div class="matched_img">
          <%= image_tag matched.user_info.image.variant(resize:'400x400'), class: "user_img" if matched.user_info.image.attached? %>
        </div>
        <div class="time">
        <%= matched.updated_at.to_s(:datetime_jp) %>
        </div>
        <div class="top">
          <p class="nickname"><%= matched.nickname %></p>
          <span>/</span>
          <p class="area"><%= matched.user_info.area.name %></p>
          <span>/</span>
          <p class="people_num"><%= matched.user_info.people_num_id %>人</p>
        </div>
      </div>
      <div class="down">
        <p class="user_info_text">ひとこと：<%= matched.user_info.text %></p>
      </div>
    </li>
  <% end %>
  </ul>
</div>
<% end %>